//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int activityLogID { get; set; }
        public string userID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
