//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGiaoHang
    {
        public string MaCTGH { get; set; }
        public string TinhTrangGiaoHang { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
        public string MaKH { get; set; }
        public string MaHD { get; set; }
        public string MaCongTy { get; set; }
    
        public virtual CongTyGiaoHang CongTyGiaoHang { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
